# Generated by Django 3.1.6 on 2022-02-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.IntegerField(choices=[(0, '東風戦'), (1, '半荘戦')])),
                ('player1', models.CharField(max_length=10)),
                ('player2', models.CharField(max_length=10)),
                ('player3', models.CharField(max_length=10)),
                ('player4', models.CharField(max_length=10)),
                ('default_score', models.IntegerField(default=25000)),
                ('is_bankruptcy', models.BooleanField(default=True)),
                ('is_kuitan', models.BooleanField(default=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_hand', models.CharField(default='1-0', max_length=5)),
                ('player1_score', models.IntegerField(default=25000)),
                ('player2_score', models.IntegerField(default=25000)),
                ('player3_score', models.IntegerField(default=25000)),
                ('player4_score', models.IntegerField(default=25000)),
                ('deposit', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('winner', models.CharField(blank=True, choices=[('player1', 'プレイヤー１'), ('player2', 'プレイヤー２'), ('player3', 'プレイヤー３'), ('player4', 'プレイヤー４')], max_length=10, null=True)),
                ('loser', models.CharField(blank=True, choices=[('player1', 'プレイヤー１'), ('player2', 'プレイヤー２'), ('player3', 'プレイヤー３'), ('player4', 'プレイヤー４')], max_length=10, null=True)),
                ('ready_player', models.CharField(blank=True, max_length=10, null=True)),
                ('waiting_player', models.CharField(blank=True, max_length=10, null=True)),
                ('pick', models.IntegerField(blank=True, choices=[(0, 'ツモ'), (1, 'ロン'), (2, '嶺上開花'), (3, '海底撈月'), (4, '河底撈魚'), (5, '搶槓'), (6, '流し満貫'), (7, '天和・地和')], null=True)),
                ('ready', models.IntegerField(blank=True, choices=[(0, '立直'), (1, '立直一発'), (2, 'ダブル立直'), (3, 'ダブル立直一発')], null=True)),
                ('closed_tile', models.CharField(blank=True, max_length=50, null=True)),
                ('melted_tile', models.CharField(blank=True, max_length=50, null=True)),
                ('win_tile', models.CharField(blank=True, max_length=5, null=True)),
                ('dora', models.CharField(blank=True, max_length=20, null=True)),
                ('win_score', models.IntegerField(default=0)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hand')),
            ],
        ),
    ]
