# Generated by Django 3.1.6 on 2022-02-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='win_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
