# Generated by Django 3.1.6 on 2022-03-02 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220225_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='id',
        ),
        migrations.AlterField(
            model_name='result',
            name='hand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.hand'),
        ),
    ]
