# Generated by Django 3.1.6 on 2022-03-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220302_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='loser',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='winner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
